const start = async () => {
	try {
		const app = await next
	} catch (e) {
		console.log(e);
	}
}